"""Export MLflow runs to a single-file, dependency-free HTML report.

The Phase-7 checklist demands an HTML exporter for the MLflow archive.
A reviewer should be able to open one ``.html`` file and inspect every
run's parameters, metrics, and tags without needing a live MLflow
tracking server. This is the reviewer-friendly counterpart to the raw
``mlruns/`` directory.

Design:

- Pure stdlib. No matplotlib, no jinja2, no pandas. The output is a
  small inline-styled HTML page.
- Works both with a live MLflow client (when ``mlflow`` is importable)
  and from a pre-loaded list of run dicts (for testing).
- Deterministic: identical inputs produce byte-identical output.
"""

from __future__ import annotations

import html
import json
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True, slots=True)
class RunRecord:
    """A flattened view of one MLflow run that the exporter consumes."""

    run_id: str
    experiment_name: str
    start_time: str
    end_time: str
    status: str
    params: Mapping[str, str] = field(default_factory=dict)
    metrics: Mapping[str, float] = field(default_factory=dict)
    tags: Mapping[str, str] = field(default_factory=dict)


def load_runs_from_mlflow(
    tracking_uri: str | None = None,
    experiment_filter: str | None = None,
) -> list[RunRecord]:
    """Read every run from a live MLflow store. Returns ``[]`` if MLflow
    is not importable."""
    try:
        import mlflow
        from mlflow.tracking import MlflowClient
    except ImportError:
        return []

    if tracking_uri:
        mlflow.set_tracking_uri(tracking_uri)
    client = MlflowClient()
    experiments = client.search_experiments()

    out: list[RunRecord] = []
    for exp in experiments:
        if experiment_filter is not None and experiment_filter != exp.name:
            continue
        runs = client.search_runs(
            experiment_ids=[exp.experiment_id],
            max_results=1000,
            order_by=["attributes.start_time DESC"],
        )
        for run in runs:
            info = run.info
            data = run.data
            out.append(
                RunRecord(
                    run_id=str(info.run_id),
                    experiment_name=str(exp.name),
                    start_time=_format_epoch(getattr(info, "start_time", 0)),
                    end_time=_format_epoch(getattr(info, "end_time", 0)),
                    status=str(info.status),
                    params=dict(data.params or {}),
                    metrics={k: float(v) for k, v in (data.metrics or {}).items()},
                    tags=dict(data.tags or {}),
                )
            )
    return out


def _format_epoch(ms: int) -> str:
    if not ms:
        return ""
    import time

    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(ms / 1000.0))


# ---------------------------------------------------------------------------
# HTML rendering
# ---------------------------------------------------------------------------


_STYLE = """
:root { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
body { margin: 24px; color: #1a1a1a; background: #fafafa; }
h1 { font-size: 22px; margin-bottom: 8px; }
.meta { color: #555; margin-bottom: 24px; }
section.experiment { background: #fff; border: 1px solid #e0e0e0; border-radius: 8px;
                     padding: 16px 20px; margin-bottom: 18px; }
section.experiment h2 { font-size: 16px; margin: 0 0 12px 0; color: #243047; }
table { border-collapse: collapse; width: 100%; font-size: 12px; }
th, td { padding: 6px 10px; border-bottom: 1px solid #eee; text-align: left; vertical-align: top; }
th { background: #f4f5f9; font-weight: 600; color: #243047; }
td.run-id { font-family: ui-monospace; font-size: 11px; color: #555; }
td.kv-cell { font-size: 11px; max-width: 360px; }
details { margin: 4px 0; }
summary { cursor: pointer; color: #2553b3; }
""".strip()


def render_html(
    *,
    title: str,
    runs: Iterable[RunRecord],
) -> str:
    """Render a self-contained HTML page summarising every run."""
    runs_by_experiment: dict[str, list[RunRecord]] = {}
    runs_list = list(runs)
    for r in runs_list:
        runs_by_experiment.setdefault(r.experiment_name, []).append(r)

    parts: list[str] = []
    parts.append("<!DOCTYPE html>")
    parts.append('<html lang="en"><head>')
    parts.append('<meta charset="utf-8">')
    parts.append(f"<title>{html.escape(title)}</title>")
    parts.append(f"<style>{_STYLE}</style>")
    parts.append("</head><body>")
    parts.append(f"<h1>{html.escape(title)}</h1>")
    parts.append(
        f'<div class="meta">Generated by hylog MLflow exporter — '
        f"{len(runs_list)} run(s) across {len(runs_by_experiment)} experiment(s)</div>"
    )

    for exp_name in sorted(runs_by_experiment):
        runs_in = runs_by_experiment[exp_name]
        parts.append('<section class="experiment">')
        parts.append(
            f'<h2>{html.escape(exp_name)} <span class="meta">({len(runs_in)} runs)</span></h2>'
        )
        parts.append("<table>")
        parts.append(
            "<thead><tr>"
            "<th>run_id</th><th>start</th><th>end</th><th>status</th>"
            "<th>params</th><th>metrics</th><th>tags</th>"
            "</tr></thead><tbody>"
        )
        for r in runs_in:
            parts.append("<tr>")
            parts.append(f'<td class="run-id">{html.escape(r.run_id[:16])}</td>')
            parts.append(f"<td>{html.escape(r.start_time)}</td>")
            parts.append(f"<td>{html.escape(r.end_time)}</td>")
            parts.append(f"<td>{html.escape(r.status)}</td>")
            parts.append(f'<td class="kv-cell">{_render_kv(r.params)}</td>')
            parts.append(f'<td class="kv-cell">{_render_kv_numbers(r.metrics)}</td>')
            parts.append(f'<td class="kv-cell">{_render_kv(r.tags)}</td>')
            parts.append("</tr>")
        parts.append("</tbody></table></section>")

    parts.append("</body></html>")
    return "\n".join(parts) + "\n"


def _render_kv(mapping: Mapping[str, str]) -> str:
    if not mapping:
        return "<em>—</em>"
    items = sorted(mapping.items())
    body = "<br>".join(
        f"<code>{html.escape(str(k))}</code>: {html.escape(str(v))}" for k, v in items
    )
    if len(items) <= 4:
        return body
    head = "<br>".join(
        f"<code>{html.escape(k)}</code>: {html.escape(str(v))}" for k, v in items[:3]
    )
    rest = "<br>".join(
        f"<code>{html.escape(k)}</code>: {html.escape(str(v))}" for k, v in items[3:]
    )
    return f"{head}<details><summary>+{len(items) - 3} more</summary>{rest}</details>"


def _render_kv_numbers(mapping: Mapping[str, float]) -> str:
    if not mapping:
        return "<em>—</em>"
    items = sorted(mapping.items())
    return "<br>".join(f"<code>{html.escape(k)}</code>: {v:.4f}" for k, v in items)


def export_html(
    *,
    out_path: Path | str,
    runs: Iterable[RunRecord] | None = None,
    tracking_uri: str | None = None,
    experiment_filter: str | None = None,
    title: str = "HyLog MLflow runs",
) -> Path:
    """Top-level helper: load runs (if not provided) and emit HTML."""
    if runs is None:
        runs = load_runs_from_mlflow(
            tracking_uri=tracking_uri,
            experiment_filter=experiment_filter,
        )
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_html(title=title, runs=runs), encoding="utf-8", newline="\n")
    return p


def runs_to_json(runs: Iterable[RunRecord]) -> str:
    """Serialise runs as canonical JSON (debugging + diffing)."""
    payload = [
        {
            "run_id": r.run_id,
            "experiment_name": r.experiment_name,
            "start_time": r.start_time,
            "end_time": r.end_time,
            "status": r.status,
            "params": dict(r.params),
            "metrics": dict(r.metrics),
            "tags": dict(r.tags),
        }
        for r in runs
    ]
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=True)


__all__ = [
    "RunRecord",
    "export_html",
    "load_runs_from_mlflow",
    "render_html",
    "runs_to_json",
]
